name: Release on Tag Push

on:
  push:
    tags:
      - v**

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get commit message and title
        id: commit
        run: |
          TITLE=$(git log -1 --pretty=format:%s)
          BODY=$(git log -1 --pretty=format:%b)
          echo "title=$TITLE" >> $GITHUB_ENV
          echo "body=$BODY" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'semeru'
          java-version: '11'

      - name: Build with Maven
        run: mvn -f chess-api/pom.xml clean package source:jar javadoc:jar -DskipTests

      - name: Find JAR files
        id: find_jars
        run: |
          BIN_JAR=$(ls chess-api/target/*.jar | grep -v sources.jar | grep -v javadoc.jar)
          SRC_JAR=$(ls chess-api/target/*-sources.jar)
          DOC_JAR=$(ls chess-api/target/*-javadoc.jar)
          POM_FILE=chess-api/pom.xml
          echo "bin_jar=$BIN_JAR" >> $GITHUB_ENV
          echo "src_jar=$SRC_JAR" >> $GITHUB_ENV
          echo "doc_jar=$DOC_JAR" >> $GITHUB_ENV
          echo "pom_file=$POM_FILE" >> $GITHUB_ENV

      - name: Upload JARs and POM to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.title }}
          body: ${{ env.body }}
          files: |
            ${{ env.bin_jar }}
            ${{ env.src_jar }}
            ${{ env.doc_jar }}
            ${{ env.pom_file }}
          draft: false
          prerelease: false
